### ISSUE TITLE
CHIRIMENのpolyfill.jsにある機能の追加

### ISSUE THREAD

**Issue by kou029w** [chirimen-oh/node-web-i2c#1]
いくつかのWeb I2C APIに存在しない関数はCHIRIMENドライバーが依存しているので対応する

- I2CPort.prototype.writeByte
- I2CPort.prototype.writeBytes
- I2CPort.prototype.readByte
- I2CPort.prototype.readBytes

**Comment by gurezo** [comment]
Echigo時代のチケット
https://github.com/chirimen-oh/any-issues/issues/156

**Comment by gurezo** [comment]
W3C
http://browserobo.github.io/WebI2C/
